# Generated by Django 4.2.11 on 2024-05-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("05:00 - 06:00", "05:00 - 06:00"),
                            ("06:00 - 07:00", "06:00 - 07:00"),
                            ("07:00 - 08:00", "07:00 - 08:00"),
                            ("08:00 - 09:00", "08:00 - 09:00"),
                            ("09:00 - 10:00", "09:00 - 10:00"),
                            ("10:00 - 11:00", "10:00 - 11:00"),
                            ("11:00 - 12:00", "11:00 - 12:00"),
                            ("12:00 - 13:00", "12:00 - 13:00"),
                            ("13:00 - 14:00", "13:00 - 14:00"),
                            ("14:00 - 15:00", "14:00 - 15:00"),
                            ("15:00 - 16:00", "15:00 - 16:00"),
                            ("16:00 - 17:00", "16:00 - 17:00"),
                            ("17:00 - 18:00", "17:00 - 18:00"),
                            ("18:00 - 19:00", "18:00 - 19:00"),
                            ("19:00 - 20:00", "19:00 - 20:00"),
                            ("20:00 - 21:00", "20:00 - 21:00"),
                            ("21:00 - 22:00", "21:00 - 22:00"),
                            ("22:00 - 23:00", "22:00 - 23:00"),
                            ("23:00 - 00:00", "23:00 - 00:00"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=13,
                    ),
                ),
                ("players_count", models.IntegerField(blank=True, null=True)),
                ("is_repetitive", models.BooleanField(default=False)),
                (
                    "event",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tournament", "Tournament"),
                            ("group_training", "Group training"),
                            ("individual_training", "Individual training"),
                            ("open_play", "Open play"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["day", "-time"],
            },
        ),
    ]
