# Generated by Django 4.2.11 on 2024-05-01 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_bookings",
                to="user.telegramuser",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("day", "time")},
        ),
    ]
